login:
    pattern:  /login/
    defaults: { _controller: OpenSkedgeBundle:Security:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

dashboard:
    pattern:  /dashboard/
    defaults: { _controller: OpenSkedgeBundle:Dashboard:index }

user_new:
    pattern:  /user/new
    defaults: { _controller: OpenSkedgeBundle:User:new }

user_view:
    pattern:  /user/{id}/
    defaults: { _controller: OpenSkedgeBundle:User:view }
    requirements:
        id: \d+

user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: OpenSkedgeBundle:User:edit }
    requirements:
        id: \d+

user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: OpenSkedgeBundle:User:delete }
    requirements:
        id: \d+
        _method:  POST

my_schedules:
    pattern:  /user/schedules/
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule:index, id: ~ }

user_schedules:
    pattern:  /user/{id}/schedules/
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule:index }
    requirements:
        id: \d+

user_schedule_pre_new:
    pattern:  /user/schedule/new
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule:precreate }

user_schedule_new:
    pattern:  /user/schedule/period/{spid}/new
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule:new }
    requirements:
        spid: \d+

user_schedule_edit:
    pattern:  /user/schedule/period/{spid}/edit
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule:edit }
    requirements:
        spid: \d+

user_schedule_delete:
    pattern:  /user/{uid}/schedule/period/{spid}/delete
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule: delete }
    requirements:
        uid: \d+
        spid: \d+

user_schedule_view:
    pattern:  /user/{uid}/schedule/period/{spid}/
    defaults: { _controller: OpenSkedgeBundle:AvailabilitySchedule:view }
    requirements:
        uid: \d+
        spid: \d+

user_employees:
    pattern:  /user/employees/
    defaults: { _controller: OpenSkedgeBundle:User:employees }

user_supervisors:
    pattern:  /user/supervisors/
    defaults: { _controller: OpenSkedgeBundle:User:supervisors }

user_colleagues:
    pattern:  /user/colleagues/
    defaults: { _controller: OpenSkedgeBundle:User:colleagues }

user_positions:
    pattern:  /user/positions/
    defaults: { _controller: OpenSkedgeBundle:Position:positions }

users:
    pattern:  /users/
    defaults: { _controller: OpenSkedgeBundle:User:index }

user:
    pattern:  /profile/
    defaults: { _controller: OpenSkedgeBundle:User:view, id: null }

areas:
    pattern:  /areas/
    defaults: { _controller: OpenSkedgeBundle:Area:index }

area_new:
    pattern:  /area/new
    defaults: { _controller: OpenSkedgeBundle:Area:new }

area_view:
    pattern:  /area/{id}/
    defaults: { _controller: OpenSkedgeBundle:Area:view }
    requirements:
        id: \d+

area_edit:
    pattern:  /area/{id}/edit
    defaults: { _controller: OpenSkedgeBundle:Area:edit }
    requirements:
        id: \d+

area_delete:
    pattern:  /area/{id}/delete
    defaults: { _controller: OpenSkedgeBundle:Area:delete }
    requirements:
        id: \d+
        _method:  POST

position_new:
    pattern:  /area/{area_id}/position/new
    defaults: { _controller: OpenSkedgeBundle:Position:new }

position_view:
    pattern:  /area/position/{id}/
    defaults: { _controller: OpenSkedgeBundle:Position:view }
    requirements:
        id: \d+

position_edit:
    pattern:  /area/position/{id}/edit
    defaults: { _controller: OpenSkedgeBundle:Position:edit }
    requirements:
        id: \d+

position_delete:
    pattern:  /area/position/{id}/delete
    defaults: { _controller: OpenSkedgeBundle:Position:delete }
    requirements:
        id: \d+
        _method:  POST

position_schedule_edit:
    pattern:  /area/position/{pid}/period/{spid}/schedule/edit
    defaults: { _controller: OpenSkedgeBundle:Schedule:edit }
    requirements:
        pid: \d+
        spid: \d+

position_schedule_view:
    pattern:  /area/position/{pid}/period/{spid}/schedule/
    defaults: { _controller: OpenSkedgeBundle:Schedule:view }
    requirements:
        pid: \d+
        spid: \d+

position_schedule_delete:
    pattern:  /area/position/{pid}/period/{spid}/schedule/delete
    defaults: { _controller: OpenSkedgeBundle:Schedule:delete }
    requirements:
        pid: \d+
        spid: \d+
        _method:  POST

clock_in:
    pattern:  /api/clock/in
    defaults: { _controller: OpenSkedgeBundle:Clock:clockIn }
    requirements:
        _method:  POST

clock_out:
    pattern:  /api/clock/out
    defaults: { _controller: OpenSkedgeBundle:Clock:clockOut }
    requirements:
        _method:  POST

schedules:
    pattern:  /schedules/
    defaults: { _controller: OpenSkedgeBundle:SchedulePeriod:index }

schedule_period_new:
    pattern:  /schedule/period/new
    defaults: { _controller: OpenSkedgeBundle:SchedulePeriod:new }

schedule_period_edit:
    pattern:  /schedule/period/{id}/edit
    defaults: { _controller: OpenSkedgeBundle:SchedulePeriod:edit }

schedule_period_delete:
    pattern:  /schedule/period/{id}/delete
    defaults: { _controller: OpenSkedgeBundle:SchedulePeriod:delete }
    requirements:
        id: \d+
        _method:  POST

schedule_period_view:
    pattern:  /schedule/period/{id}/
    defaults: { _controller: OpenSkedgeBundle:SchedulePeriod:view }

reports:
    pattern:  /reports/
    defaults:  { _controller: OpenSkedgeBundle:Report:index }

default:
    pattern: /
    defaults: { _controller: OpenSkedgeBundle:Default:index }


