parameters:
    notify_mailer.class: OpenSkedge\AppBundle\Mailer\TwigMailer
    security.authentication.provider.api_token_auth.class: OpenSkedge\AppBundle\Security\Authentication\Provider\ApiTokenAuthenticationProvider

services:
    app_settings:
        class: OpenSkedge\AppBundle\Services\AppSettingsService
        arguments: [@doctrine.orm.default_entity_manager]

    clock_utils:
        class: OpenSkedge\AppBundle\Services\ClockService
        arguments: [@doctrine.orm.default_entity_manager, @dt_utils]

    dt_utils:
        class: OpenSkedge\AppBundle\Services\DateTimeUtils
        arguments: [@app_settings]

    notify_mailer:
        class: %notify_mailer.class%
        arguments: [@mailer, @twig, @logger, @app_settings, { senderEmail: %sender_email% }]
        lazy: true

    request:
        class: Symfony\Component\HttpFoundation\Request

    stats:
        class: OpenSkedge\AppBundle\Services\StatsService
        arguments: [@doctrine.orm.default_entity_manager, @dt_utils]

    app_settings.twig.extension:
        class: OpenSkedge\AppBundle\Twig\Extension\SettingsExtension
        arguments: [@app_settings]
        tags:
            - { name: 'twig.extension' }

    page.twig.extension:
        class: OpenSkedge\AppBundle\Twig\Extension\PageExtension
        arguments:  [@request]
        tags:
            - { name: 'twig.extension' }

    worker_command:
        class: OpenSkedge\AppBundle\Command\WorkerRunCommand
        tags:
            - { name: monolog.logger, channel: worker }

    security.authentication.provider.api_token_auth:
        class: %security.authentication.provider.api_token_auth.class%
        arguments:  ["", @security.user_checker, "", @security.encoder_factory, %security.authentication.hide_user_not_found%]
